In [1]:
#Markovljev model izvora informacije 

In [8]:
import numpy as np
from numpy.linalg import matrix_power

In [9]:
#2. Koliko će kupaca čokolade tvrtke A kupovati čokoladu tvrtke A nakon 3 tjedna reklamiranja?

In [10]:
P0 = np.matrix([0.3, 0.7])
P = np.matrix([[0.9, 0.1], [0.6, 0.4]])

In [11]:
P_3 = matrix_power(P, 3)
P1 = np.matmul(P0, P_3)

In [12]:
P_3

matrix([[0.861, 0.139],
        [0.834, 0.166]])

In [13]:
P1

matrix([[0.8421, 0.1579]])

In [14]:
#3. Koliko će kupaca čokolade tvrtke A kupovati čokoladu tvrtke A nakon 100 tjedna reklamiranja?

In [15]:
P_100 = matrix_power(P, 100)
P100 = np.matmul(P0, P_100)

In [16]:
P_100

matrix([[0.85714286, 0.14285714],
        [0.85714286, 0.14285714]])

In [17]:
P100

matrix([[0.85714286, 0.14285714]])